### ISSUE TITLE
Update `.gitignore` and `workflows` "pr" (I tired but I don't have perms).

### ISSUE THREAD

**Issue by dsm-72** [fastai/nbprocess-template#12]
## .gitignore
```.gitignore
# ......................................
# Distribution / packaging
.Python
env/
build/
conda/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
# ...................................
```
## deploy.yaml
```yml
# .github/workflows/deploy.yaml
name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/quarto-ghp@master
        with:
          version: '3.10'
```
## test.yaml
```yml
# .github/workflows/test.yaml
name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/nbdev-ci@master
        with:
          version: '3.10'

```
